#+TITLE:  Readme for StatsHelp package
#+AUTHOR: Dirk Oliver Theis, Theoretical Computer Science, University of Tartu, Estonia
#+DATE: Fri Aug 18 17:39:39 CEST 2023

Julia package that helps with statistics for random processes

#+BEGIN_QUOTE
This Julia package is part of the Julia package repository [[https://github.com/dojt/DOT_JuliaPackageRegistry][~DOT_JuliaPackageRegistry~]].  It relies on packages stored
there, and can be added from there[fn:1].  (The convenient way to do that is through the standard Julia package
[[https://github.com/GunnarFarneback/LocalRegistry.jl][LocalRegistry.jl]].
#+END_QUOTE

Unfortunately, GitHub renders Org only incompletely.  To view the literate source text, goto the HTML export,
[[./DOT_StatsHelp.html][DOT_StatsHelp.html]].


[fn:1] ... as soon as the first stable version is ready.

* Version History

/Time goes up!/


** *v0.3.0*  Added JSON-IO to mean estimation object

    + Todo: *Document it!* In particular, mention that the work space and the r,s indices are lost from exporting
      to JSON and re-importing -- so this is cannot be used for /interrupting/ a stats collection process.


** *v0.2.0*  First working-ish version

    + Basic implementations for mean estimating; with tests

    + Basic implementations for max approximating processes; /without/ tests

** *v0.1.0*  Initial version -- dosn't do anything yet 😅

----------------------------------------------------------------------------------------------------


* /Org/-anization of This Repository

  The source code in this repository is based on Emacs' Org-mode literate programming.  The actual editable
  source-text is the file
  #+BEGIN_CENTER
  [[./DOT_StatsHelp.org][~DOT_StatsHelp.org~]]
  #+END_CENTER
  All docs, discussions of the source code, and the actual source code are in that file, and are "tangled" into the
  files in the ~./src/~ and ~./test/~ folders.

# Local Variables:
# fill-column: 115
# End:
